# Exercise-6

1. Create one hot encoding of an array. <br> For example For an array ([2, 3, 2, 2, 2, 1]). Output should be <br>
   <br> array(
         [[ 0.,  1.,  0.],
         [ 0.,  0.,  1.],
         [ 0.,  1.,  0.],
         [ 0.,  1.,  0.],
         [ 0.,  1.,  0.],
         [ 1.,  0.,  0.]])

In [8]:
import numpy as np

data = np.array([2, 3, 2, 2, 2, 1])
data -= 1
shape = (data.size, data.max() + 1)

one_hot = np.zeros(shape)
rows = np.arange(data.size)
one_hot[rows, data] = 1
print(one_hot)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


2.Drop all missing values from an array <br><br> Input: np.array([1,2,3,np.nan,5,6,7,np.nan]) <br> Desired Output: array([ 1.,2.,3.,5.,6.,7.])

In [13]:
import numpy as np

arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
arr = arr[~np.isnan(arr)]
print(arr)

[1. 2. 3. 5. 6. 7.]


3. Find Local maxima from an array. <br><br>Input: a = np.array([1, 3, 7, 1, 2, 6, 0, 1]) <br>Desired Output: array([2, 5])

In [15]:
import numpy as np
from scipy.signal import argrelextrema

data = np.array([1, 3, 7, 1, 2, 6, 0, 1])
maximums = argrelextrema(data, np.greater)
print(maximums)

(array([2, 5]),)


4.From the given 1d array arr, generate a 2d matrix using strides, <br> 
For example for an array ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]) with a window length of w=4 and strides of s=2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..] <br>
w and s will be provided by user

In [2]:
import numpy as np

def get_conv(arr, w, s):
    indices = np.arange(0, len(arr), s)
    mat = []
    for i in indices:
        if i + w < len(arr):
            mat.append(arr[i:i+w])
        else:
            temp = arr[i:]
            diff = w - len(temp)
            temp = np.concatenate((temp, np.zeros(diff, np.int64)), axis=0)
            mat.append(temp)
    return np.array(mat)

a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
print(get_conv(a, 4, 2))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]
 [12 13 14  0]
 [14  0  0  0]]
