# **1.**
Create a function to check whether numpy array has Zero values or not.


In [5]:
import numpy as np 

def check_array_has_all_zeros(arr):
  for i in arr:
    if i != 0:
      return False
    
  return True

arr = np.zeros(5)
print(arr)
check_array_has_all_zeros(arr)

[0. 0. 0. 0. 0.]


True

# **2.**
Consider an array contains marks of students. Find the median and mean of students who got passing marks.


In [52]:
import random

arr = []
for i in range(0, 100):
  arr.append(random.randint(0, 100) + random.randint(0, random.randint(0, 20)) - random.randint(random.randint(0, 8), 10))


# remove the marks from array which are less than the passing marks
PASSING_MARKS = 33
passing_marks_array = []
for i in arr:
  if (i > PASSING_MARKS):
    passing_marks_array.append(i)

nparr = np.array(passing_marks_array)
nparr.sort()
print("Mean: ", nparr.mean())
print("Median: ", nparr[len(nparr) // 2])


Mean:  68.14492753623189
Median:  70


# **3.**
Consider an array containing date of birth of students (Use np.datetime64('2018-02-01')). Find the age of all students. If age is 18 label it First, if it is 19, label it Second, if it is 20, label it Third, if it is 21, label it Fourth.


In [96]:
import random

today = np.datetime64("today")
arr = np.array(np.datetime64('2000-02-01'))

for i in range(15):
  e = np.array(np.datetime64(str(random.randint(1999, 2002)) + "-" + str(random.randint(10, 12)) + "-" + str(random.randint(10, 30))))
  arr = np.append(arr, e)

print(today)
print(arr)

for i in arr:
  year_np_diff = (today - i).astype('timedelta64[Y]')
  year_diff = int(str(year_np_diff).split(" ")[0])
  
  if year_diff == 18:
    print("First")
  elif year_diff == 19:
    print("Second")
  elif year_diff == 20:
    print("Third")
  elif year_diff == 21:
    print("Forth")
  else:
    print("Something else")
  


2021-04-29
['2000-02-01' '2000-10-19' '1999-11-29' '2002-11-25' '2000-10-19'
 '2002-12-24' '2002-10-25' '2001-11-19' '2002-10-15' '2000-10-26'
 '2001-12-12' '1999-11-10' '1999-10-16' '1999-10-23' '1999-11-15'
 '1999-11-13']
Forth
Third
Forth
First
Third
First
First
Second
First
Third
Second
Forth
Forth
Forth
Forth
Forth


# **4.**
Create a function to sort 2d Array by a column.

In [80]:
nparr = np.array([[1, 2, 3], [7, 9, 5], [0, 3, 8]])

nparr = nparr.transpose()

nparr = nparr[ : , nparr[0].argsort()]
print(nparr.transpose())

[[0 3 8]
 [1 2 3]
 [7 9 5]]
